<?php

/**
*Implements hook_permission().
*/
function cron_monitor_permission() {
  return array(
    'administer cronmonitor' => array(
      'title' => t('Administer Cron Monitor'),
      'description' => t('Perform administration tasks for Cron Monitor.'),
    ),
  );
}



function cron_monitor_menu() {
  $items ['admin/config/cronmonitor'] = array(
    'title' => 'Cron Monitor Settings',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer cronmonitor'),
    'page arguments' => array('cronmonitor_admin_form'),
    'type' => MENU_NORMAL_ITEM,
  );
   return $items;
}

/**
*Administration form for Cron Monitor.
*/
function cronmonitor_admin_form($form, &$form_state) {
	$form['cronmonitor_enable'] = array(
		'#type' =>'checkbox', 
		'#title' => t('Enable Cron Monitor'),
		'#default_value' => variable_get('cronmonitor_enable',0),
	);
 	$form['cronmonitor_email_text'] = array(
		'#type' => 'textfield',
		'#title' => t('Message to send with Cron Monitor email'), 
		'#description' => t('Enter the text to be sent with cron monitor email message.'),
		'#default_value' => variable_get('cronmonitor_email_text', ''), 
		'#size' => 80, 
		'#maxlength' => 128, 
		'#required' => TRUE,

	);


return system_settings_form($form);
}

/**
*Implements hook_menu().
*/

function cronmonitor_cron() {
	if (variable_get('cronmonitor_enable', 0)) {
		//Send cronmonitor email.
		drupal_mail('cronmonitor', 'cronmonitor_email', 'name@domain.com', language_default());
	}
}

/**
*Implements hook_menu().
*/
function cronmonitor_mail($key, &$message, $params) {
	switch ($key) {
		case 'cronmonitor_email';
		$message['subject'] = t('This is a cron monitor report');
		$message['body'][] = t('This is cronmonitor report from @site-name', array('@site-name' => variable_get('site_name', 'drupal_test.com')));
		$message['body'][] = t('This is a crin monitor report');
		break;
	}
}