<?php

/*
 * Implementation of hook_menu()
 */
function adfero_test_menu() {
    // page for form submission
    // path location
    $items['adfero-form'] = array(
        // page title
        'title' => 'Adfero Form',
        // page description for the menu system.
        'description' => 'Page creation for form',
        // function called on path visit
        'page callback' => 'drupal_get_form',
        'page arguments' => array('input_simple_form'),
        'access callback' => TRUE, 
        // permissions required to view page
        'access arguments' => array('access content'),
    );
    // page for submission results view
    $items['adfero-data'] = array(
        // page title
        'title' => 'Adfero Form results',
        'description' => 'Page creation for submission data access',
        'page callback' => 'adfero_test_content',
        'access callback' => TRUE, 
        // permissions required to view page
        'access arguments' => array('access content'),
    );  
    return $items;
}

/* Page agruments function */

function input_simple_form($form, &$form_state) {
     $form['name']=array(
        '#type'=>'textfield',
        '#title'=>t('Enter your name'),
        '#description'=>t('Your first name goes here')
      );
    $form['last_name']=array(
        '#type'=>'textfield',
        '#title'=>t('Enter your Last name'),
        '#description'=>t('Your Last name goes here')
      );
    
    $form['email']=array(
        '#type'=>'textfield',
        '#title'=>t('Enter your email'),
        '#description'=>t('Your email goes here')
      );
    $form['country']=array(
        '#type'=>'select',
        '#title'=>t('Select your country'),
        '#options'=>array('USA'=>'USA','Brasil'=>'Brasil','France'=>'France','Italy'=>'Italy')
      );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
        );
    return $form;
}


// function input_simple_form_alter($form, &$form_state) {
//   $form['last_name']['#description']=>t('Your  here');
// }
/*
/////////////Form validation
*/

function input_simple_form_validate($form, &$form_state) {

  if(empty($form_state['values']['name']))
     form_set_error('name','Name cannot be empty');
  else if(empty($form_state['values']['last_name']))
     form_set_error('last_name','Last name cannot be empty');
  else if(filter_var($form_state['values']['email'], FILTER_VALIDATE_EMAIL) == false)
    form_set_error('email','Email is not valid');
}

/**
 * Implements input_simple_form_submit().
 */
function input_simple_form_submit($form, &$form_state) {
  global $user; 
  #dsm($form);
  // Inserting data values into database.
  db_insert('adfero_table')
    ->fields(array(   
      'name' => $form_state['values']['name'], 
      'last_name' => $form_state['values']['last_name'],   
      'email' => $form_state['values']['email'],  
      'country' => $form_state['values']['country'],  
    ))
    ->execute();
  drupal_set_message("Submitted successfully");  

}

/*
//Table display format for submitted data
*/
function adfero_test_content() {
  global $user;
  //restriction for amdinistrator access only
  if(!in_array("administrator", $user->roles)) {
    return FALSE;
  }

  $output  = '<table class="reference" style="width:100%">';
  $output .= '<tbody><tr>';
  $output .= '<th>Name</th>';
  $output .= '<th>Last Name</th>';
  $output .= '<th>Email</th>    ';
  $output .= '<th>Country</th>';
  $output .= '</tr>';

  $result = db_query("SELECT * FROM {adfero_table}");
  // Result is returned as a iterable object that returns a stdClass object on each iteration
  foreach ($result as $record) { 
    //row
    $output .= '<tr>';

    //data
    $output .= '<td>' . $record->name . '</td>';
    $output .= '<td>' . $record->last_name . '</td>';
    $output .= '<td>' . $record->email . '</td>';
    $output .= '<td>' . $record->country . '</td>';
    //close row
    $output .= '</tr>';
    
    /*
    // Display results in json format
    */
    $json_obj[] = $record;
  }

  $output .= '</tbody></table>';
  $output .= '<br/> <br/> <br/> <br/> ';
  $output .= '<div class ="json-format"> Data in JSON Format </div><div>';
  $output .= json_encode($json_obj);
  $output .= '</div>';


  return $output;
}